---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Get Vector version
      ansible.builtin.command: "vector --version"
      changed_when: false
      register: vector_version1
    - name: Print Vector version
      ansible.builtin.debug: var=vector_version1
    - name: Assert Vector instalation
      assert:
        that: "'{{ vector_version1.rc }}' == '0'"

    - name: Validation Vector configuration
      ansible.builtin.command: "vector validate --no-environment --config-yaml /vector.yml"
      changed_when: false
      register: vector_validate
    - name: Print Vector validate
      ansible.builtin.debug:  var=vector_validate
    - name: Assert Vector validate config
      assert:
        that: "'{{ vector_validate.rc }}' == '0'"
