---
# tasks file for vector-role
- name: Download Vector
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.x86_64.rpm"
    dest: "./vector-{{ vector_version }}-1.x86_64.rpm"
- name: Install Vector
  become: true
  ansible.builtin.yum:
    name: "vector-{{ vector_version }}-1.x86_64.rpm"
- name: Template config
  ansible.builtin.template:
    src: vector.yml.j2
    dest: vector.yml
    mode: 0755
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    validate: vector validate --no-environment --config-yaml %s
- name: create systemd unit
  become: true
  ansible.builtin.template:
    src: vector.service.j2
    dest: /etc/systemd/system/vector.service
    mode: 0755
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
- name: Start service
  become: true
  ansible.builtin.systemd:
    name: vector
    state: started
    daemon_reload: true
